In [84]:
# AJUSTES INICIALES

import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd

scope = ["https://www.googleapis.com/auth/spreadsheets",
         "https://www.googleapis.com/auth/drive"]

credentials = ServiceAccountCredentials.from_json_keyfile_name('/home/diego/Documents/A-PARA/3-Resources/Programming_projects/1PROJECTS/Streamlit-Chatbot-Interface/gs_credentials.json', scope)

client = gspread.authorize(credentials)

# sheet = client.create("TodoDieces")
# sheet.share('al426641@uji.es', perm_type='user', role='writer')

In [58]:
# ACTUALIZAR DATOS LOCALES

sheet = client.open("TodoDieces").sheet1

data = sheet.get_all_values()

if len(data) > 0:
    headers = data[0]
    rows = data[1:]

    df = pd.DataFrame(rows, columns=headers)
    df.to_csv('/home/diego/Documents/A-PARA/3-Resources/Programming_projects/1PROJECTS/Streamlit-Chatbot-Interface/data.csv', index=False)
    print("File created successfully.")
else:
    print("No data available in the sheet.")

File created successfully.

In [ ]:
# ACTUALIZAR DATOS EN LA NUBE

sheet = client.open("TodoDieces").sheet1

df = pd.read_csv('/home/diego/Documents/A-PARA/3-Resources/Programming_projects/1PROJECTS/Streamlit-Chatbot-Interface/data.csv')

df = df.astype(str)  # Convert float values to strings

df.columns.values.tolist()
df.values.tolist()

sheet.update([df.columns.values.tolist()] + df.values.tolist())

In [64]:
# GETTING INDIVIDUAL VALUES (NOT RECOMMENDED FOR THE API)

# Getting a cell value

print(sheet.cell(1, 1).value) # A1
print(sheet.cell(2, 1).value) # A2

# Getting a row value
print(sheet.row_values(1)) # A1, B1, C1, D1, E1
print(sheet.col_values(1)) # A1, A2, A3, A4, A5


# Cell formula
print(sheet.cell(1, 1, value_render_option='FORMULA').value)

PRUEBA
LAB
['PRUEBA', 'ASIGNATURA', 'FECHA', 'DIEGO', 'ISMAEL', 'GUILLEM', 'DAVID', 'NICOLÁS']
PRUEBA

In [66]:
# GETTING ALL VALUES

list_of_lists = sheet.get_all_values()
print(list_of_lists)

list_of_dicts = sheet.get_all_records()
print(list_of_dicts)



# CLEAR THE SHEET

sheet.clear()

[['PRUEBA', 'ASIGNATURA', 'FECHA', 'DIEGO', 'ISMAEL', 'GUILLEM', 'DAVID', 'NICOLÁS'], ['LAB', 'MAT', '25/09/2023', '7.0', '10.0', '10.0', '10.0', '6.0'], ['LAB', 'ETK', '29/09/2023', '10.0', '0.0', '10.0', '10.0', '10.0'], ['LAB', 'EST', '30/09/2023', '8.75', '10.0', '10.0', '10.0', '10.0'], ['PAR', 'PRG', '11/10/2023', '10.0', '0.0', '5.0', '10.0', '5.0'], ['LAB', 'MAT', '16/10/2023', '10.0', '10.0', '10.0', '10.0', '10.0'], ['PAR', 'PRG', '18/10/2023', '9.5', '9.6', '9.8', '10.0', '4.9'], ['LAB', 'ETK', '23/10/2023', 'nan', 'nan', 'nan', 'nan', 'nan'], ['LAB', 'EST', '29/10/2023', '10.0', '10.0', '10.0', '9.2', '10.0'], ['LAB', 'MAT', '30/10/2023', '7.0', '10.0', '9.5', '10.0', '10.0'], ['PAR', 'MAT', '06/11/2023', '10.0', '10.0', '10.0', '10.0', '10.0'], ['LAB', 'ETK', '10/11/2023', 'nan', 'nan', 'nan', 'nan', 'nan'], ['LAB', 'MAT', '13/11/2023', '10.0', '10.0', '10.0', '10.0', '10.0'], ['PAR', 'PRG', '15/11/2023', '7.1', '0.0', '1.7', '9.7', 'nan'], ['LAB', 'ETK', '17/11/2023', 'nan', 'nan', 'nan', 'nan', 'nan'], ['PAR', 'PRG', '22/11/2023', '7.5', '0.0', '0.5', '7.5', '7.5'], ['LAB', 'MAT', '27/11/2023', '10.0', '10.0', '10.0', '10.0', '10.0'], ['LAB', 'EST', '30/11/2023', '10.0', '10.0', '10.0', '7.5', 'nan'], ['PAR', 'MAT', '11/12/2023', '7.5', '8.5', '10.0', '7.5', '7.5'], ['PAR', 'PRG', '13/12/2023', 'nan', 'nan', 'nan', 'nan', 'nan'], ['PAR', 'EST', '18/12/2023', 'nan', 'nan', 'nan', 'nan', 'nan']]
[{'PRUEBA': 'LAB', 'ASIGNATURA': 'MAT', 'FECHA': '25/09/2023', 'DIEGO': 7.0, 'ISMAEL': 10.0, 'GUILLEM': 10.0, 'DAVID': 10.0, 'NICOLÁS': 6.0}]

In [57]:
# MODIFICAR DATOS EN LA HOJA DE CÁLCULO

# sheet.update_cell(1, 1, "Hello World!")
# sheet.update("A1", "Hello World!")
# sheet.update("A1:B2", [[1, 2], [3, 4]])

# sheet.insert_row(["Hello", "World"], 1)         # Insertar al principio

# sheet.append_row(["Hello", "World"])            # Insertar al final

# sheet.delete_row(1)                            # Eliminar fila 1
# sheet.delete_rows(1, 2)                        # Eliminar filas 1 y 2
# sheet.delete_columns(1)                        # Eliminar columna 1
sheet.resize(rows=2, cols=2)                    # Redimensionar hoja de cálculo

# sheet.format("A1:B2", {"textFormat": {"bold": True}})  # Formatear celdas

{'spreadsheetId': '1k9LHCKdbE1AL79bnydpKJLtVkHiddqKltTV5uhgn-hQ',
 'replies': [{}]}

In [86]:
df = pd.read_csv('/home/diego/Documents/A-PARA/3-Resources/Programming_projects/1PROJECTS/Streamlit-Chatbot-Interface/data.csv')

for col_person in range(3, len(df.columns)):
    for fila_nota in range(0, len(df)):
        if pd.isna(df.iloc[fila_nota, col_person]):
            df.iloc[fila_nota, col_person] = input("Introduce la nota de " + df.columns[col_person] + " en " + df.iloc[fila_nota, 0] + " de la asignatura " + df.iloc[fila_nota, 1] + " el dia " + df.iloc[fila_nota, 2] + ": ")

df

   PRUEBA ASIGNATURA       FECHA DIEGO ISMAEL GUILLEM DAVID NICOLÁS
0     LAB        MAT  25/09/2023   7.0   10.0    10.0  10.0     6.0
1     LAB        ETK  29/09/2023  10.0    0.0    10.0  10.0    10.0
2     LAB        EST  30/09/2023  8.75   10.0    10.0  10.0    10.0
3     PAR        PRG  11/10/2023  10.0    0.0     5.0  10.0     5.0
4     LAB        MAT  16/10/2023  10.0   10.0    10.0  10.0    10.0
5     PAR        PRG  18/10/2023   9.5    9.6     9.8  10.0     4.9
6     LAB        ETK  23/10/2023
7     LAB        EST  29/10/2023  10.0   10.0    10.0   9.2    10.0
8     LAB        MAT  30/10/2023   7.0   10.0     9.5  10.0    10.0
9     PAR        MAT  06/11/2023  10.0   10.0    10.0  10.0    10.0
10    LAB        ETK  10/11/2023
11    LAB        MAT  13/11/2023  10.0   10.0    10.0  10.0    10.0
12    PAR        PRG  15/11/2023   7.1    0.0     1.7   9.7
13    LAB        ETK  17/11/2023
14    PAR        PRG  22/11/2023   7.5    0.0     0.5   7.5     7.5
15    LAB        MAT  27/11/2023  10.0   10.0    10.0  10.0    10.0
16    LAB        EST  30/11/2023  10.0   10.0    10.0   7.5
17    PAR        MAT  11/12/2023   7.5    8.5    10.0   7.5     7.5
18    PAR        PRG  13/12/2023
19    PAR        EST  18/12/2023